services:
  zaptal:
    build:
      context: .
      dockerfile: Dockerfile
    image: zaptal-website:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    restart: unless-stopped
